config/routes.rb
Rails.application.routes.draw do
  
  resources :homes, path: '/', only: [:index]

  get 'register', to: 'accounts#new'

  post 'register', to: 'accounts#create'

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :pahlawans, path: '/pahlawan'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pahlawan.rb
class Pahlawan < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(resource_params)
    user.save
    redirect_to register_path
  end

  private

  def resource_params
    params.require(:user).permit(:fullname, :username, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      nil
    end
  end

  def user_logged_in?
    if current_user
      true
    else
      redirect_to login_path, notice: 'Please log in first'
      return false
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/pahlawans_controller.rb
class PahlawansController < ApplicationController
 
  before_action :user_logged_in?

  def index
    @pahlawans = Pahlawan.all
    @pahlawan = Pahlawan.new
  end

  def show
    id = params[:id]
    @pahlawan = Pahlawan.find(id)
  end
  
  def create
    pahlawan = Pahlawan.new(resource_params)
    pahlawan.save
    redirect_to pahlawans_path
  end

  def edit
    @pahlawan = Pahlawan.find(params[:id])
  end

  def update
    @pahlawan = Pahlawan.find(params[:id])
    @pahlawan.update(resource_params)
    redirect_to pahlawans_path
  end

  def destroy
    @pahlawan = Pahlawan.find(params[:id])
    @pahlawan.destroy
    redirect_to pahlawans_path
  end

  private

  def resource_params
    params.require(:pahlawan).permit(:name, :place, :birth, :description, :photo) 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    username = params[:username]
    password = params[:password]

    user = User.find_by(username: username)

    if user
      if user.authenticate(password)
        session[:user_id] = user.id
        redirect_to pahlawans_path, notice: 'You are logged in'
      else
        redirect_to login_path, notice: 'Username/password is still wrong'
      end
    else
      redirect_to login_path, notice: 'Username/password is still wrong'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'You was logged out'
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pahlawans_helper.rb
module PahlawansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/accounts/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2 class="text-center">Register</h2>
  
  <% if flash[:notice].present? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <%= form_for @user, url: register_path do |f| %>
    <div class="form-group">
      <%= f.label :fullname %>
      <%= f.text_field :fullname, class: 'form-control input-sm' %>
    </div>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control input-sm' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control input-sm' %>
    </div>
    <%= f.submit "Register", class: 'btn btn-sm btn-primary' %>
    <%= link_to "Back", homes_path, class: 'btn btn-sm btn-default' %>
  <% end %>
</div>

app/views/homes/index.html.erb
<style>
  .App {
    margin-top: 70px;
    display: flex;
    justify-content: center;
  }
</style>

<div class="App">
  <h2>You have an account?</h2>
  <p><%= link_to "Log In", login_path, class: 'btn btn-sm btn-primary' %></p>
  <h2>Please register here.</h2>
  <p><%= link_to "Register", register_path, class: 'btn btn-sm btn-success' %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PahlawanBangsa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/flatly/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pahlawans/edit.html.erb
 <div class="col-md-5">
    <div class="panel panel-primary">
      <div class="panel-header"><h3 class="text-center">Input Pahlawan</h3></div>
      <div class="panel-body">
        <%= form_for @pahlawan do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control input-sm' %>
          </div>
          <div class="form-group">
            <%= f.label :place %>
            <%= f.text_field :place, class: 'form-control input-sm' %>
          </div>
          <div class="form-group">
            <%= f.label :birth %>
            <%= f.text_field :birth, class: 'form-control input-sm' %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control input-sm' %>
          </div>
          <div class="form-group">
            <%= f.label :photo %>
            <%= f.text_field :photo, class: 'form-control input-sm' %>
          </div>
          <%= f.submit "Update Pahlawan", class: 'btn btn-sm btn-success' %>
        <% end %>
      </div>
    </div>

app/views/pahlawans/index.html.erb
<style>
h2 {
  margin-bottom: 50px;
  background-color: #21817f;
  padding: 10px;
  border: 1px solid #a3a3a3;
  border-radius: 10px;
  color: #fff;
}

table {
  border: 1px solid #a3a3a3;
  border-radius: 20px;
}

table thead th {
  padding: 5px;
  background-color: #21817f;
  color: #fff;
}

.pahlawan-status {
  margin-bottom: 50px;
}
</style>
<div class="col-md-12">
  
  <h2 class="text-center">Pahlawan Bangsa</h2>

  <div class="col-md-12 pahlawan-status">
    <% if current_user %>
      <div class="pull-left">
        <p>Halo, <%= current_user.fullname %></p>
      </div>
      <div class="pull-right">
        <%= link_to "Log out", logout_path(current_user), method: :delete, class: 'btn btn-sm btn-danger' %>
      </div>
    <% end %>
  </div>

  <div class="col-md-5">
    <div class="panel panel-primary">
      <div class="panel-header"><h3 class="text-center">Input Pahlawan</h3></div>
      <div class="panel-body">
        <%= form_for @pahlawan do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control input-sm' %>
          </div>
          <div class="form-group">
            <%= f.label :place %>
            <%= f.text_field :place, class: 'form-control input-sm' %>
          </div>
          <div class="form-group">
            <%= f.label :birth %>
            <%= f.text_field :birth, class: 'form-control input-sm' %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control input-sm' %>
          </div>
          <div class="form-group">
            <%= f.label :photo %>
            <%= f.text_field :photo, class: 'form-control input-sm' %>
          </div>
          <%= f.submit "Add Pahlawan", class: 'btn btn-sm btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-7">
    <table class="table table-striped table-hover">
      <thead>
        <th class="text-center">No.</th>
        <th class="text-center">Image</th>
        <th class="text-center">Name</th>
        <th class="text-center">Actions</th>
      </thead>
      <tbody>
        <% @pahlawans.each do |pahlawan| %>
        <tr>
          <td class="text-center"><%= pahlawan.id %></td>
          <td class="text-center"><img src="<%= pahlawan.photo %>" width=80 height=80 alt="<%= pahlawan.name %>" />
          </td>
          <td><%= pahlawan.name %></td>
          <td class="text-center">
            <%= link_to raw("<i class='glyphicon glyphicon-eye-open'></i>"), pahlawan_path(pahlawan), class: 'btn btn-sm btn-primary' %> 
            <%= link_to raw("<i class='glyphicon glyphicon-pencil'></i>"), edit_pahlawan_path(pahlawan), class: 'btn btn-sm btn-warning' %>
            <%= link_to raw("<i class='glyphicon glyphicon-trash'></i>"), pahlawan_path(pahlawan), method: :delete, class: 'btn btn-sm btn-danger' %>
          </td>
          </td>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/pahlawans/new.html.erb
<h1>Pahlawans#new</h1>
<p>Find me in app/views/pahlawans/new.html.erb</p>

app/views/pahlawans/show.html.erb
<div class="col-md-5">
  <h3><%= @pahlawan.name %></h3>
  <img src="<%= @pahlawan.photo %>" alt="<%= @pahlawan.name %>"/>
  <h4><%= @pahlawan.place %>, <%= @pahlawan.birth %></h4>
  <p>
    <%= @pahlawan.description %>
  </p>
</div>